version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing basic packages...
  build:
    commands:
      - echo Building a simple HTML file...
      - mkdir -p build
      - echo "<h1>Deployment Test Successful 🚀</h1>" > build/index.html

artifacts:
  files:
    - build/**/*
    - appspec.yml
    - scripts/install.sh