version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd backend && npm install && cd ..
      - mkdir -p build
      - cp -r backend/* build/
      - cp -r backend/scripts build/
      - cp appspec.yml build/
      - chmod +x build/scripts/install_node.sh
      

  build:
    commands:
      - echo Build step complete

artifacts:
  files:
    - build/**/*