version: 0.2

env:
  variables:
    S3_BUCKET: s3frontendbuild1 # your existing S3 bucket name

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd frontend && npm install && cd ..
      - cd backend && npm install && cd ..
  
  build:
    commands:
      - echo Building frontend...
      - cd ../frontend && npm run build
      - echo Zipping backend...
      - cd ../backend && zip -r ../backend.zip .

artifacts:
  files:
    - backend.zip
    - appspec.yml
    - scripts/**
  secondary-artifacts:
    frontend:
      base-directory: frontend/build
      files:
        - '**/*'