version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd frontend && npm install && cd ..
      - cd backend && npm install && cd ..

  build:
    commands:
      - echo Building frontend...
      - cd frontend && npm run build && cd ..
      - echo Zipping backend for deployment...
      - mkdir -p build/backend
      - cp -r backend appspec.yml build/backend/
      - cd build/backend && zip -r ../backend.zip . && cd ../..

artifacts:
  files:
    - build/backend.zip
    
  secondary-artifacts:
    frontendArtifact:
      base-directory: frontend/build
      files:
        - '**/*'