version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - cd backend
      - npm install
  build:
    commands:
      - echo Build complete. Preparing artifact...
      - zip -r ../backend-build.zip .
artifacts:
  files:
    - backend-build.zip